name: VSCodeESLintLanguageService
kind: pipeline
type: docker

steps:
- name: install
  image: node
  commands:
  - npm install
- name: lint
  image: node
  commands:
  - npm run lint
- name: build debug
  image: node
  commands:
  - npm run build
  - npm run clean
- name: build release
  image: node
  commands:
  - npm run build
  - npm run clean
- name: build extension
  image: node
  commands:
  - npx vsce package
  when:
    event:
    - tag
- name: publish extension
  image: node
  environment:
    ACCESS_TOKEN:
      from_secret: AZURE_TOKEN
  commands:
  - npx vsce publish --pat $ACCESS_TOKEN
  when:
    event:
    - tag
- name: release notes
  image: ubuntu
  commands:
  - export HeadingPattern='/## \(.* \(v[0-9.]*\|\[.*\]\)\)/'
  - cp -f CHANGELOG.md ReleaseNotes.md
  - sed -i "0,$${HeadingPattern}{ $${HeadingPattern}P ; d } ; $${HeadingPattern},\$d" ReleaseNotes.md
  - cp -f ReleaseNotes.md ReleaseTitle.md
  - sed -i "2,\$d ; s$${HeadingPattern}\\\\1/" ReleaseTitle.md
  when:
    event:
    - tag
- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: GITHUB_TOKEN
    files:
      - "*.vsix"
    title: ReleaseTitle.md
    note: ReleaseNotes.md
  when:
    event:
    - tag

trigger:
  ref:
  - refs/heads/**
  - refs/pull/**
  - refs/tags/**
  event:
  - push
  - pull_request
  - tag
